name: Compile Arduino Sketch

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v2.0.0

      - name: Install Arduino Core
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr

      - name: Compile Arduino Sketch
        run: |
          arduino-cli compile --fqbn arduino:avr:uno ArdulinkProtocol/ArdulinkProtocol.ino

      - name: Save hex-artifact
        uses: actions/upload-artifact@v4
        with:
          name: uno-hex
          path: ArdulinkProtocol/ArdulinkProtocol.ino.hex

