name: Run Pytest

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt

      - name: Run behave in the 'tests' folder
        working-directory: tests
        env:
          SKETCH_FILE: ../ArdulinkProtocol/ArdulinkProtocol.ino
        run: |
          behave -f pretty -f html-pretty

      - name: Test Report
        uses: dorny/test-reporter@31a54ee7ebcacc03a09ea97a7e5465a47b84aea5 # v1
        if: (success() || failure()) && github.event_name != 'pull_request' && github.actor != 'dependabot[bot]'  # run this step even if previous step failed
        with:
          name: Tests Report
          path: "tests/test-results/*.xml"
          reporter: java-junit

