name: Release Firmware

on:
  push:
    tags:
      - 'v*'
    
jobs:
  compile_and_test:
    uses: ./.github/workflows/compile-and-test-firmware.yml

  release:
    runs-on: ubuntu-latest
    needs: compile_and_test
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ardulink-firmware-uno
          path: ./artifact

      - name: Unzip artifact
        run: unzip ./artifact/ardulink-firmware-uno.zip -d ./ArdulinkProtocol

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "ArdulinkProtocol/ArdulinkProtocol.ino,ArdulinkProtocol/ArdulinkProtocol.ino.hex"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          name: ${{ github.ref_name }}
          body: |
            New release for Ardulink Protocol.
          draft: true
          prerelease: false
